global.press_right = keyboard_check(ord("D"))
global.press_left = keyboard_check(ord("A"))
global.press_up = keyboard_check(ord("W"))
global.press_down = keyboard_check(ord("S"))
global.press_mouse_left = mouse_check_button(mb_left)
global.press_mouse_right = mouse_check_button_pressed(mb_right)
global.escape_key_press = keyboard_check_pressed(vk_escape)